### ISSUE TITLE
JBoss Error

### ISSUE THREAD

**Issue by macfol** [macfol/Kamienica#94]
> 2:56:24,927 ERROR [org.jboss.msc.service.fail](ServerService Thread Pool -- 61) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./Kamienica: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./Kamienica: java.lang.RuntimeException: java.lang.IllegalArgumentException: Failed to register servlet with name 'dispatcher'.Check if there is another servlet registered under the same name.
>   at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
>   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)
>   at org.jboss.threads.JBossThread.run(JBossThread.java:320)
> Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Failed to register servlet with name 'dispatcher'.Check if there is another servlet registered under the same name.
>   at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:224)
>   at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
>   at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
>   ... 6 more
> Caused by: java.lang.IllegalArgumentException: Failed to register servlet with name 'dispatcher'.Check if there is another servlet registered under the same name.
>   at org.springframework.util.Assert.notNull(Assert.java:112)
>   at org.springframework.web.servlet.support.AbstractDispatcherServletInitializer.registerDispatcherServlet(AbstractDispatcherServletInitializer.java:93)
>   at org.springframework.web.servlet.support.AbstractDispatcherServletInitializer.onStartup(AbstractDispatcherServletInitializer.java:69)
>   at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:175)
>   at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:184)
>   ... 8 more
> 
> 12:56:24,931 ERROR [org.jboss.as.controller.management-operation](Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "Kamienica.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./Kamienica" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./Kamienica: java.lang.RuntimeException: java.lang.IllegalArgumentException: Failed to register servlet with name 'dispatcher'.Check if there is another servlet registered under the same name.
>     Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Failed to register servlet with name 'dispatcher'.Check if there is another servlet registered under the same name.
>     Caused by: java.lang.IllegalArgumentException: Failed to register servlet with name 'dispatcher'.Check if there is another servlet registered under the same name."}}
> 12:56:24,963 INFO  [org.jboss.as.server](ServerService Thread Pool -- 34) WFLYSRV0010: Deployed "Kamienica.war" (runtime-name : "Kamienica.war")
> 12:56:24,965 INFO  [org.jboss.as.controller](Controller Boot Thread) WFLYCTL0183: Service status report
> WFLYCTL0186:   Services which failed to start:      service jboss.undertow.deployment.default-server.default-host./Kamienica: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./Kamienica: java.lang.RuntimeException: java.lang.IllegalArgumentException: Failed to register servlet with name 'dispatcher'.Check if there is another servlet registered under the same name.

**Comment by macfol** [comment]
Checked on wildfly 10.1 and works fine

**Comment by championheng** [comment]
I have the same problem. How do I solve it?

**Comment by macfol** [comment]
To be honest I didn't do much. Which version are trying to run?
